#!/usr/bin/env bash
set -euo pipefail

# Reproduces the previous default ablation run:
# a3_sfilm_swav_contactbits_pose_track2_6500_mb16_lr1e3_400
export GO2_POLICY_USE_HEIGHT_ENCODER="${GO2_POLICY_USE_HEIGHT_ENCODER:-0}"
export GO2_POLICY_TEACHER_CONTEXT_MODE="${GO2_POLICY_TEACHER_CONTEXT_MODE:-current_privileged}"
export GO2_POLICY_USE_TEACHER_MIXER="${GO2_POLICY_USE_TEACHER_MIXER:-0}"
export GO2_POLICY_CRITIC_USE_PRIVILEGED_OBS="${GO2_POLICY_CRITIC_USE_PRIVILEGED_OBS:-1}"
export GO2_POLICY_DETACH_CRITIC_CONTEXT="${GO2_POLICY_DETACH_CRITIC_CONTEXT:-1}"

export GO2_POLICY_USE_ACTOR_FILM="${GO2_POLICY_USE_ACTOR_FILM:-1}"
export GO2_POLICY_USE_STABLE_SWAV="${GO2_POLICY_USE_STABLE_SWAV:-1}"
export GO2_POLICY_STABLE_LATENT_DIM="${GO2_POLICY_STABLE_LATENT_DIM:-8}"
export GO2_POLICY_SWAV_NUM_PROTOTYPES="${GO2_POLICY_SWAV_NUM_PROTOTYPES:-64}"
export GO2_ALG_STABLE_SWAV_COEF="${GO2_ALG_STABLE_SWAV_COEF:-0.01}"

export GO2_PRIVILEGED_INCLUDE_BODY_CONTACT_BITS="${GO2_PRIVILEGED_INCLUDE_BODY_CONTACT_BITS:-1}"
export GO2_ALG_NUM_MINI_BATCHES="${GO2_ALG_NUM_MINI_BATCHES:-16}"
export GO2_ALG_LEARNING_RATE="${GO2_ALG_LEARNING_RATE:-0.001}"
export GO2_ALG_STUDENT_ENCODER_LEARNING_RATE="${GO2_ALG_STUDENT_ENCODER_LEARNING_RATE:-0.001}"

export GO2_ALG_USE_EMA_TEACHER="${GO2_ALG_USE_EMA_TEACHER:-0}"
export GO2_ALG_EMA_TEACHER_DECAY="${GO2_ALG_EMA_TEACHER_DECAY:-0.995}"
export GO2_ALG_EMA_TEACHER_WARMUP_UPDATES="${GO2_ALG_EMA_TEACHER_WARMUP_UPDATES:-100}"

export GO2_REWARD_COLLISION_SCALE="${GO2_REWARD_COLLISION_SCALE:--1.0}"
export GO2_REWARD_FEET_REGULATION_SCALE="${GO2_REWARD_FEET_REGULATION_SCALE:--0.05}"
export GO2_REWARD_SIMILAR_TO_DEFAULT_SCALE="${GO2_REWARD_SIMILAR_TO_DEFAULT_SCALE:--0.01}"

export NUM_ENVS="${NUM_ENVS:-6500}"
export MAX_ITERATIONS="${MAX_ITERATIONS:-400}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-go2_moe_cts_ablation}"
export RUN_NAME="${RUN_NAME:-default_sfilm_swav_contactbits_pose_track2_6500_mb16_lr1e3_400}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "${SCRIPT_DIR}/run_ablation_stable_film.sh" "$@"
