#!/usr/bin/env bash
set -euo pipefail

export GO2_POLICY_USE_HEIGHT_ENCODER="${GO2_POLICY_USE_HEIGHT_ENCODER:-1}"
export GO2_POLICY_TEACHER_CONTEXT_MODE="${GO2_POLICY_TEACHER_CONTEXT_MODE:-current_privileged}"
export GO2_POLICY_CRITIC_USE_PRIVILEGED_OBS="${GO2_POLICY_CRITIC_USE_PRIVILEGED_OBS:-1}"
export GO2_POLICY_DETACH_CRITIC_CONTEXT="${GO2_POLICY_DETACH_CRITIC_CONTEXT:-1}"

export GO2_POLICY_USE_STABLE_SWAV="${GO2_POLICY_USE_STABLE_SWAV:-1}"
export GO2_POLICY_STABLE_LATENT_DIM="${GO2_POLICY_STABLE_LATENT_DIM:-8}"
export GO2_POLICY_SWAV_NUM_PROTOTYPES="${GO2_POLICY_SWAV_NUM_PROTOTYPES:-64}"
export GO2_ALG_STABLE_SWAV_COEF="${GO2_ALG_STABLE_SWAV_COEF:-0.01}"

export RUN_NAME="${RUN_NAME:-a1_no_mixer_height_encoder_swav8p64_rawcritic_1024_400}"

exec ./scripts/run_ablation_teacher_height_encoder_no_mixer.sh "$@"
